name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ammaarah14
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23FFD43B&color_dots=%230B1020,%233B167D,%235420A8,%237436D6,%23A855F7
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23FFD43B&color_dots=%230B1020,%233B167D,%235420A8,%237436D6,%23A855F7

      - name: Publish snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}